[build]
  publish = "."
  command = "npm install"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/ai/rss-tips"
  to = "/.netlify/functions/ai-rss-tips"
  status = 200

[[redirects]]
  from = "/api/rss/check-rss"
  to = "/.netlify/functions/rss-check"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 5000

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"